### PR TITLE
Add static type checking to the Python skeleton

### PR DESCRIPTION
**Pull request by felddy**
# 

## 🗣 Description

**Static type hinting is optional.  Don't freak.**

Add [PEP 484](https://www.python.org/dev/peps/pep-0484/) type hints to the example. 
Add [mypy](https://github.com/python/mypy) static type checker to the pre-commit hooks.

Once/If this is approved, I will backport the `pre-commit` and `.gitignore` changes to the generic skeleton. 

## 💭 Motivation and Context

I can across a section of the [18-F Python development guide](https://engineering.18f.gov/python/) that discussed static checking.  There are a lot of upsides to type hinting and few downsides.  Also I miss the safety of a statically-typed language. 

As mentioned in the 18-F guide (and soon our own): 

> ...It’s reasonable to default to using type annotations when they make your intent clearer (i.e. as a form of documentation). We suggest using a static analysis tool to catch logic bugs, but only where it’s practical. 

## 🧪 Testing

Previous tests pass.
Added `mypy` to the pre-commit linters.  It will throw errors and warnings if type hints are used and violated.  Otherwise it should be a no-op.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
Shouldn't this go in [cisagov/skeleton-generic](https://cisagov/skeleton-generic)?  We want static type linting whether you're creating a library or writing a one-off python script.

**Comment by felddy** [comment]
> Shouldn't this go in [cisagov/skeleton-generic](https://cisagov/skeleton-generic)? We want static type linting whether you're creating a library or writing a one-off python script.

See my backport comment in the description.

**Comment by jsf9k** [comment]
> See my backport comment in the description.

Why backport?  Just put it in skeleton-generic and trickle it down.

**Comment by felddy** [comment]
> Why backport? Just put it in skeleton-generic and trickle it down.

Because I wanted to tie the syntax changes in the Python source code to the linter addition as a demonstration of what static type hinting entails.  

I was not assuming this PR would necessarily get approved, and didn't want to have two PRs to demonstrate it.

**Review by jsf9k — APPROVED** [review]
Let's do this thing!

**Review by dav3r — APPROVED** [review]
Nifty- I'm interested to see how this goes. 🌔

**Pull request merged**
