### PR TITLE
Add Support for Running as Python Module

### PR DESCRIPTION
**Pull request by mcdonnnj**
## 🗣 Description

This PR adds a `__main__.py` file to allow the Python package to be run as a Python module. It also removes the shebang (`#!`) and executable bit from the main Python file in the project. Lastly it expands a `pip` option in one of the requirements files.

## 💭 Motivation and Context

There has been a habit of making Python files in our Python libraries executable, configuring them with a shebang, and adding a `if __name__ == "__main__"` block. None of these should really be done for library files. Calling a script directly can cause issues when it is written as part of a Python package, and so it should be avoided. If we include a script written for standalone use in one of our Python projects, it will need to have an appropriate shebang and the executable bit added. Only files not written as part of the package should have this done.

Most of our Python projects have a console script configured in `setup.py`. An example is this project's:
https://github.com/cisagov/skeleton-python-library/blob/a5378b01689137ac6c78aef957348e87aa12f875/setup.py#L91
Any of our Python packages that are configured to have a main console script should also support running the package as a module with the Python executable (`python -m package_name`). This allows a fallback method if there is an issue with installing or running the console script.

## 🧪 Testing

Automated tests pass and I confirmed I was able to call the script as expected with both the console script and as a Python module.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
So how does the script work when run standalone?  Does it get a shebang added to it by `setuptools`?

**Comment by mcdonnnj** [comment]
> 
> 
> So how does the script work when run standalone? Does it get a shebang added to it by `setuptools`?

I'm not sure I understand what you're asking. Do you mean calling the file directly with `python filename.py`, or do you mean `python -m package_name`?

**Comment by jsf9k** [comment]
> > So how does the script work when run standalone? Does it get a shebang added to it by `setuptools`?
> 
> I'm not sure I understand what you're asking. Do you mean calling the file directly with `python filename.py`, or do you mean `python -m package_name`?

There used to be a file in this repo that had a shebang, indicating that it could be run directly as `./file_with_shebang`.  I took your PR description to be saying that this was still possible.  I'm asking how that works, since the script no longer has a shebang.  Does a shebang get added by `setuptools`?

**Comment by mcdonnnj** [comment]
> 
> 
> > > So how does the script work when run standalone? Does it get a shebang added to it by `setuptools`?
> > 
> > 
> > I'm not sure I understand what you're asking. Do you mean calling the file directly with `python filename.py`, or do you mean `python -m package_name`?
> 
> There used to be a file in this repo that had a shebang, indicating that it could be run directly as `./file_with_shebang`. I took your PR description to be saying that this was still possible. I'm asking how that works, since the script no longer has a shebang. Does a shebang get added by `setuptools`?

I apologize for the unclear nature of the PR description and I have updated it to better reflect the change. In this case if a file *must* be written to run standalone, you would need to add the shebang and executable bit. This should only be done when absolutely necessary. Python packages are not designed around running a single piece of it as a Python script, and we should not include that functionality unless absolutely necessary.

**Comment by jsf9k** [comment]
> > > > So how does the script work when run standalone? Does it get a shebang added to it by `setuptools`?
> > > 
> > > 
> > > I'm not sure I understand what you're asking. Do you mean calling the file directly with `python filename.py`, or do you mean `python -m package_name`?
> > 
> > 
> > There used to be a file in this repo that had a shebang, indicating that it could be run directly as `./file_with_shebang`. I took your PR description to be saying that this was still possible. I'm asking how that works, since the script no longer has a shebang. Does a shebang get added by `setuptools`?
> 
> I apologize for the unclear nature of the PR description and I have updated it to better reflect the change. In this case if a file _must_ be written to run standalone, you would need to add the shebang and executable bit. This should only be done when absolutely necessary. Python packages are not designed around running a single piece of it as a Python script, and we should not include that functionality unless absolutely necessary.

Then how does `pip`, for instance, handle this case?  The `pip` Python package installs a standalone executable for pip.  You can also run `pip` via `python -m pip`.  It seems to handle the standalone case just fine.

**Comment by jsf9k** [comment]
> > > > > So how does the script work when run standalone? Does it get a shebang added to it by `setuptools`?
> > > > 
> > > > 
> > > > I'm not sure I understand what you're asking. Do you mean calling the file directly with `python filename.py`, or do you mean `python -m package_name`?
> > > 
> > > 
> > > There used to be a file in this repo that had a shebang, indicating that it could be run directly as `./file_with_shebang`. I took your PR description to be saying that this was still possible. I'm asking how that works, since the script no longer has a shebang. Does a shebang get added by `setuptools`?
> > 
> > 
> > I apologize for the unclear nature of the PR description and I have updated it to better reflect the change. In this case if a file _must_ be written to run standalone, you would need to add the shebang and executable bit. This should only be done when absolutely necessary. Python packages are not designed around running a single piece of it as a Python script, and we should not include that functionality unless absolutely necessary.
> 
> Then how does `pip`, for instance, handle this case? The `pip` Python package installs a standalone executable for pip. You can also run `pip` via `python -m pip`. It seems to handle the standalone case just fine.

I got it now.  Thanks for clearing this up @mcdonnnj!

**Comment by mcdonnnj** [comment]
> 
> 
> > > > > > So how does the script work when run standalone? Does it get a shebang added to it by `setuptools`?
> > > > > 
> > > > > 
> > > > > I'm not sure I understand what you're asking. Do you mean calling the file directly with `python filename.py`, or do you mean `python -m package_name`?
> > > > 
> > > > 
> > > > There used to be a file in this repo that had a shebang, indicating that it could be run directly as `./file_with_shebang`. I took your PR description to be saying that this was still possible. I'm asking how that works, since the script no longer has a shebang. Does a shebang get added by `setuptools`?
> > > 
> > > 
> > > I apologize for the unclear nature of the PR description and I have updated it to better reflect the change. In this case if a file _must_ be written to run standalone, you would need to add the shebang and executable bit. This should only be done when absolutely necessary. Python packages are not designed around running a single piece of it as a Python script, and we should not include that functionality unless absolutely necessary.
> > 
> > 
> > Then how does `pip`, for instance, handle this case? The `pip` Python package installs a standalone executable for pip. You can also run `pip` via `python -m pip`. It seems to handle the standalone case just fine.
> 
> I got it now. Thanks for clearing this up @mcdonnnj!

Updated the PR description based on our conversation. Thanks for pointing out what wasn't making sense so i could clarify.

**Review by dav3r — APPROVED** [review]
Excellent work @mcdonnnj 🚀

**Review by hillaryj — APPROVED** [review]
Coveralls is complaining about a decrease in test coverage, but the changes themselves look good!

**Comment by mcdonnnj** [comment]
> 
> 
> Coveralls is complaining about a decrease in test coverage, but the changes themselves look good!

The added `__main__.py` file is not being tested, hence the decrease. However, that file only includes and runs a method that is already being tested, so it should be fine.

**Review by felddy — APPROVED** [review]
Thanks for being clear about this.  I like it all!  ⭐

**Comment by felddy** [comment]
Is there no way we can get our coverage back on `__main__.py` ? 

Something similar to:
https://medium.com/opsops/how-to-test-if-name-main-1928367290cb

**Comment by mcdonnnj** [comment]
> 
> 
> Is there no way we can get our coverage back on `__main__.py` ?
> 
> Something similar to:
> https://medium.com/opsops/how-to-test-if-name-main-1928367290cb

Only for you do I pursue true greatness @felddy . Please see d79989a.

**Pull request merged**
